apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: asia-south1-docker.pkg.dev/psychic-etching-466000-n9/webapp/webapp:latest
        ports:
        - containerPort: 80
