apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
