name: Build & Deploy

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/webapp/webapp:latest"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"

      - name: Update Kubernetes deployment YAML
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/webapp/webapp:latest"
          sed -i "s|image: .*|image: $IMAGE|" k8s/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.email "msgtovpragavan@gmail.com"
          git config --global user.name "ragavanvp"
          git add k8s/deployment.yaml
          git diff --cached --quiet || git commit -m "Update deployment image to $IMAGE"
          git push
